# Generated by Django 4.2.30 on 2026-05-04 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficiaire', models.CharField(max_length=255)),
                ('type_travaux', models.CharField(choices=[('isolation', 'Isolation'), ('chauffage', 'Chauffage'), ('pompe à chaleur', 'Pompe à chaleur')], max_length=50)),
                ('volume', models.FloatField()),
                ('prime', models.FloatField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
