# Generated by Django 4.2.30 on 2026-05-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='type_travaux',
            field=models.CharField(choices=[('ISOLATION', 'Isolation'), ('CHAUFFAGE', 'Chauffage'), ('POMPE À CHALEUR', 'Pompe à chaleur')], max_length=50),
        ),
    ]
