# Generated by Django 4.2.30 on 2026-05-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dossier_type_travaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='type_travaux',
            field=models.CharField(max_length=100),
        ),
    ]
